id: P010723
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:21:34.430376
source_metadata:
  id: bdr:W4997
  title: རྩོད་ལན་མདོར་བསྡུས་རིགས་ལམ་རབ་གསལ་དེ་ཉིད་སྣང་བྱེད།
  author: ''
  volumes:
    1bfa1747bcbc43a6b5fc1b95eae461e6:
      image_group_id: I2780
      title: ''
      volume_number: 1
      total_pages: 252
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
